#! /usr/bin/env bash

function usage() {
  echo
  echo "usage: `basename $0` [options] {zip-file}"
  echo
  echo "   zip-file      : simple (i.e. flat hierarchy) .zip file with exactly"
  echo "                   one .xml file and (possibly) multiple binary files"
  echo
  echo " possible options:"
  echo
  echo "   --validate    : test deposit only"
  echo "   -u user       : sword user name allowed to do deposits [curr. '${user}']"
  if [ -z "${pw}" ]; then
    echo "   -p passwd     : sword password of sword user [curr. not set!]"
  else
    echo "   -p passwd     : sword password of sword user [curr. '***']"
  fi
  echo "   -h host       : sword host http address [curr. '${pubman_host}']"
  echo "   -s sword-api  : sword api root (aka opus instance) [curr. '${sword_api}']"
  echo "   -c collection : sword collection where to deposit [curr. '${collection_id}']" 
  echo "   -d            : debug switch; if given, no delivery at all(!) [curr. '${debug}']"
  echo
  echo " Currently using '${pubman_host}/${sword_api}/deposit?collection=${collection_id}'"
  echo " as SWORD delivery point."
  echo
  exit -1
}

debug="false"
x_no_op="false"
pubman_host="http://qa-pubman.mpdl.mpg.de"
sword_api="pubman/faces/sword-app"              # /sword/deposit"
collection_id="escidoc:persistent3" 
user="bertelmann"
pw=""

xmlstarlet=`which xmlstarlet`
xml_pp=`which xml_pp`
head=`which head`
cat=`which cat`
cut=`which cut`
curl=`which curl`
zip=`which zip`
unzip=`which unzip`
zipgrep=`which zipgrep`
md5sum=`which md5sum`
mktemp=`which mktemp`
wc=`which wc`
getopt=`which getopt`

${getopt} --test >/dev/null
if [ $? -ne 4 ]; then
  echo "error: 'getopt --test' failed in this environment, stop."
  exit 1
fi

parsed=`${getopt} --options dvh:c:u:p:s: --longoptions debug:,host:,collection:,user:,passwd:,sword:,validate --name "$0" -- "$@"`
if [ $? -ne 0 ]; then usage ; fi

eval set -- "${parsed}"
while true; do
  case "$1" in
       -d|--debug) debug="true" ; shift ;;
    -v|--validate) x_no_op="true" ; shift ;;
        -u|--user) user="$2" ; shift 2 ;;
       -s|--sword) sword_api="$2"; shift 2 ;;
      -p|--passwd) pw="$2"; shift 2 ;;
  -c|--collection) collection_id="$2"; shift 2 ;;
        -h|--host) pubman_host="$2"; shift 2 ;;
               --) shift ; break ;;
                *) echo "Internal error!" ; exit 1 ;;
  esac
done

if [ $# -ge 1 ]; then
  zip_file="$1"
else
  usage
fi


if [ -z "${pw}" ]; then
  read -p "[sword password] for $user: " -s pw
  echo
fi

x_packaging="http://purl.org/escidoc/metadata/schemas/0.1/publication"

abs_xsl="./Util/nlm_jats2escidoc_xml.xsl"
abs_xsl_add="./Util/add_files2escidoc_xml.xsl"
pkg_fmt="https://datahub.deepgreen.org/FilesAndJATS"
has_xml=`${zipgrep} "DOCTYPE article" ${zip_file} | ${wc} -l`

if [ ${has_xml} -eq 1 ]; then
  is_jrnl=`${zipgrep} "//NLM//DTD Journal " ${zip_file} | ${wc} -l`
  is_jats=`${zipgrep} "//NLM//DTD JATS " ${zip_file} | ${wc} -l`
  is_rsc=`${zipgrep} "//RSC//DTD RSC " ${zip_file} | ${wc} -l`
  if [ ${is_jrnl} -eq 1 ]; then
    abs_xsl="./Util/nlm_jats2escidoc_xml.xsl"
    pkg_fmt="https://datahub.deepgreen.org/FilesAndJATS"
  elif [ ${is_jats} -eq 1 ]; then
    abs_xsl="./Util/nlm_jats2escidoc_xml.xsl"
    pkg_fmt="https://datahub.deepgreen.org/FilesAndJATS"
  elif [ ${is_rsc} -eq 1 ]; then
    abs_xsl="./Util/rsc_rsc2opus_xml.xsl"
    pkg_fmt="https://datahub.deepgreen.org/FilesAndRSC"
  else
    echo "error: no valid .xml (Journal or JATS or RSC) in zip archive found: stop."
    exit -2
  fi
else
  echo "error: no valid (or too many?!) .xml (Journal xor JATS xor RSC) in zip archive found: stop."
  exit -3
fi

echo "`basename $0`: packaging format in zip archive found:"
echo "`basename $0`: ${pkg_fmt}"

tmp_dir=`${mktemp} -q -d`
trap "rm -rf ${tmp_dir}" 0 2 3 15

${unzip} -q ${zip_file} -d "${tmp_dir}/xfer"


meta_xml="`ls -1 ${tmp_dir}/xfer/*.xml | ${head} -1`"
${cat} ${meta_xml} | ${xmlstarlet} -q tr ${abs_xsl} | ${xml_pp} >"${tmp_dir}/escidoc.xml"
## for f in "${tmp_dir}"/xfer/*; do
##   [ "${f%.xml}" != "${f}" ] && continue
##   MD5=`${md5sum} --binary "${f}" | ${cut} -d" " -f1`
##   FL=`basename ${f}`
##   ${cat} "${tmp_dir}/escidoc.xml" | ${xmlstarlet} -q tr --omit-decl ${abs_xsl_add} -s md5="${MD5}" -s file="${FL}" | ${xml_pp} >"${tmp_dir}/tmp.xml"
##  mv "${tmp_dir}/tmp.xml" "${tmp_dir}/escidoc.xml"
## done
rm -f ${meta_xml}
## mv "${tmp_dir}/opus.xml" ${meta_xml}
mv "${tmp_dir}/escidoc.xml" "${tmp_dir}/xfer/escidoc.xml"
${zip} -j -r "${tmp_dir}/package.zip" "${tmp_dir}/xfer" 

MD5=`${md5sum} --binary "${tmp_dir}/package.zip" | ${cut} -d" " -f1`
echo "`basename $0`: md5sum: ${MD5}"

if [ "${debug}" = "true" ]; then
  cp "${tmp_dir}/xfer/escidoc.xml" .
  cp "${tmp_dir}/package.zip" escidoc.zip
  exit 1
fi

## header="Content-Type: application/zip"

echo
echo ${curl} --verbose --header "X-Verbose: true" --header "X-No-Op: ${x_no_op}" --header "X-Packaging: ${x_packaging}" --header "Content-Type: application/zip" --header "Content-MD5: ${MD5}" --data-binary "@${tmp_dir}/package.zip" -u "${user}:***" "${pubman_host}/${sword_api}/deposit?collection=${collection_id}"
${curl} --verbose --header "X-Verbose: true" --header "X-No-Op: ${x_no_op}" --header "X-Packaging: ${x_packaging}" --header "Content-Type: application/zip" --header "Content-MD5: ${MD5}" --data-binary "@${tmp_dir}/package.zip" -u "${user}:${pw}" "${pubman_host}/${sword_api}/deposit?collection=${collection_id}"
## ${curl} -i -s -u "$user:$pw" -X POST "${opus4_host}${sword_api_deposit}" -F "content=@${tmp_dir}/package.zip;type=application/zip;md5=${MD5}"

#echo
#echo "Temporary files still available at '${tmp_dir}'."
#rm -rf ${tmp_dir}

